"use client";

import { useEffect, useState, type ReactNode } from "react";
import { ArrowLeft, ScrollText } from "lucide-react";

export default function TermsPage() {
  const [lang, setLang] = useState<"en" | "ar">("en");

  useEffect(() => {
    const stored = localStorage.getItem("applyfast_locale");
    if (stored === "ar") setLang("ar");
  }, []);

  const toggleLang = () => {
    const next = lang === "en" ? "ar" : "en";
    setLang(next);
    localStorage.setItem("applyfast_locale", next);
    document.documentElement.dir = next === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = next;
  };

  const isAr = lang === "ar";

  return (
    <main className="min-h-screen bg-[#0a0f0e] text-white" dir={isAr ? "rtl" : "ltr"}>
      <header className="sticky top-0 bg-[#0a0f0e]/90 backdrop-blur-md border-b border-white/[0.04] z-10">
        <div className="max-w-3xl mx-auto px-4 py-4 flex items-center justify-between">
          <a
            href="/"
            className="flex items-center gap-2 text-white/50 hover:text-emerald-400 transition-colors text-sm"
          >
            <ArrowLeft className="h-4 w-4" />
            {isAr ? "العودة إلى ApplyFast" : "Back to ApplyFast"}
          </a>
          <button
            onClick={toggleLang}
            className="text-xs text-white/40 hover:text-emerald-400 transition-colors px-3 py-1.5 rounded-lg border border-white/10 hover:border-emerald-500/30"
          >
            {isAr ? "English" : "العربية"}
          </button>
        </div>
      </header>

      <div className="max-w-3xl mx-auto px-4 py-16">
        <div className="flex items-center gap-3 mb-3">
          <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center">
            <ScrollText className="h-5 w-5 text-emerald-400" />
          </div>
          <h1 className="text-3xl font-bold text-white">
            {isAr ? "شروط الاستخدام" : "Terms of Service"}
          </h1>
        </div>
        <p className="text-white/40 text-sm mb-12">
          {isAr ? "آخر تحديث: يونيو 2026" : "Last updated: June 2026"}
        </p>

        {isAr ? <TermsAR /> : <TermsEN />}
      </div>

      <footer className="border-t border-white/[0.04] py-6">
        <div className="max-w-3xl mx-auto px-4 flex items-center justify-between text-xs text-white/30">
          <p>&copy; 2026 ApplyFast AI</p>
          <div className="flex gap-4">
            <a href="/privacy" className="hover:text-emerald-400 transition-colors">
              {isAr ? "الخصوصية" : "Privacy"}
            </a>
            <a href="/terms" className="hover:text-emerald-400 transition-colors">
              {isAr ? "الشروط" : "Terms"}
            </a>
          </div>
        </div>
      </footer>
    </main>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-semibold text-white mb-3">{title}</h2>
      <div className="space-y-3 text-white/60 text-sm leading-relaxed">{children}</div>
    </section>
  );
}

function Bullet({ items }: { items: string[] }) {
  return (
    <ul className="space-y-2">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2">
          <span className="text-emerald-400 mt-0.5 flex-shrink-0">•</span>
          {item}
        </li>
      ))}
    </ul>
  );
}

function TermsEN() {
  return (
    <div>
      <Section title="1. Acceptance of Terms">
        <p>
          By accessing or using ApplyFast (&ldquo;the Service&rdquo;), you agree to be bound by
          these Terms of Service. If you do not agree, do not use the Service.
        </p>
      </Section>

      <Section title="2. Description of Service">
        <p>
          ApplyFast is an AI-powered job application assistant that helps you generate tailored
          application fields, ATS score analyses, cover letter snippets, and interview preparation
          questions based on your CV and a job description.
        </p>
        <p>
          Results are generated by artificial intelligence (DeepSeek / OpenAI) and are provided
          for informational and assistance purposes only. You are responsible for reviewing all
          generated content before submission to any employer.
        </p>
      </Section>

      <Section title="3. Free Tier & Credits">
        <Bullet
          items={[
            "The free tier provides 3 AI generations per IP address per 24-hour period — no signup required.",
            "Additional usage requires purchasing credits via Lemon Squeezy ($3 for 1 credit, $9 for 5 credits).",
            "Credits are tied to license keys. Keep your license key safe — we cannot recover lost keys.",
            "Credits do not expire and have no set expiry date, but may be subject to service changes.",
          ]}
        />
      </Section>

      <Section title="4. Payments & Refunds">
        <p>
          Payments are processed by Lemon Squeezy. By making a purchase, you agree to Lemon
          Squeezy&apos;s terms.
        </p>
        <Bullet
          items={[
            "If the AI output is clearly incorrect or fails to process your CV, contact us within 7 days for a full refund.",
            "Refunds are issued at our discretion for other dissatisfaction — we aim to be fair.",
            "Refunds are not issued for credits already successfully consumed.",
            "Contact: iziyad.alfahhad@gmail.com",
          ]}
        />
      </Section>

      <Section title="5. Acceptable Use">
        <p>You agree not to:</p>
        <Bullet
          items={[
            "Use ApplyFast to create fraudulent, deceptive, or misleading job applications",
            "Attempt to bypass the credit system, rate limits, or license validation",
            "Automate requests in a way that disrupts the service for others",
            "Reverse-engineer, extract, or reproduce the AI prompts or system infrastructure",
            "Submit content that is illegal, offensive, or violates third-party rights",
            "Resell, sublicense, or commercially redistribute the service without permission",
          ]}
        />
      </Section>

      <Section title="6. AI-Generated Content Disclaimer">
        <p>
          Output from ApplyFast is generated by AI and may contain inaccuracies, errors, or
          omissions. We make no warranties — express or implied — about the accuracy,
          completeness, or fitness of any generated content.
        </p>
        <p>
          ApplyFast does <strong className="text-white/70">not</strong> guarantee interview
          callbacks, job offers, or application success. You are solely responsible for the
          content you submit to employers.
        </p>
      </Section>

      <Section title="7. Intellectual Property">
        <Bullet
          items={[
            "Your CV, job descriptions, and application materials remain entirely your property.",
            "AI-generated output produced using your inputs is yours to use freely.",
            "The ApplyFast platform, brand, and underlying systems are owned by ApplyFast and may not be copied or imitated.",
          ]}
        />
      </Section>

      <Section title="8. Limitation of Liability">
        <p>
          ApplyFast is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranty
          of any kind. To the maximum extent permitted by applicable law, ApplyFast and its
          operators shall not be liable for any indirect, incidental, special, or consequential
          damages arising from use of — or inability to use — the Service, including but not
          limited to missed employment opportunities or data processing errors.
        </p>
      </Section>

      <Section title="9. Service Availability & Modifications">
        <p>
          We reserve the right to modify, suspend, or discontinue any part of the Service at any
          time. We will make reasonable efforts to notify users of material changes. Continued use
          after notice of changes constitutes acceptance.
        </p>
      </Section>

      <Section title="10. Governing Law">
        <p>
          These Terms are governed by and construed in accordance with the laws of the{" "}
          <strong className="text-white/70">Kingdom of Saudi Arabia</strong>. Any disputes shall
          be subject to the exclusive jurisdiction of Saudi Arabian courts, unless otherwise
          required by applicable law in your jurisdiction.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these Terms?{" "}
          <a href="mailto:iziyad.alfahhad@gmail.com" className="text-emerald-400 hover:underline">
            iziyad.alfahhad@gmail.com
          </a>
        </p>
      </Section>
    </div>
  );
}

function TermsAR() {
  return (
    <div dir="rtl">
      <Section title="١. قبول الشروط">
        <p>
          باستخدامك لـ ApplyFast («الخدمة»)، فإنك توافق على الالتزام بشروط الاستخدام هذه.
          إذا كنت لا توافق، يرجى التوقف عن استخدام الخدمة.
        </p>
      </Section>

      <Section title="٢. وصف الخدمة">
        <p>
          ApplyFast هي أداة مساعدة لتقديم طلبات التوظيف مدعومة بالذكاء الاصطناعي. تُساعدك على
          إنشاء محتوى طلب التوظيف المخصص، وتحليل التوافق مع أنظمة ATS، وصياغة خطاب التقديم،
          والتحضير للمقابلات — بناءً على سيرتك الذاتية ووصف الوظيفة.
        </p>
        <p>
          المخرجات مُولَّدة بالذكاء الاصطناعي وتُقدَّم لأغراض المساعدة فقط. أنت مسؤول عن
          مراجعة جميع المحتوى المُولَّد قبل تقديمه لأي جهة.
        </p>
      </Section>

      <Section title="٣. المجانية والرصيد">
        <Bullet
          items={[
            "يتيح المستوى المجاني ٣ عمليات توليد لكل عنوان IP خلال ٢٤ ساعة — دون اشتراك.",
            "الاستخدام الإضافي يتطلب شراء رصيد عبر Lemon Squeezy ($3 للطلب، $9 لخمسة طلبات).",
            "الرصيد مرتبط بمفاتيح الترخيص. احتفظ بمفتاحك — لا يمكننا استرجاع المفاتيح المفقودة.",
            "الرصيد لا تاريخ انتهاء له حالياً، لكنه قد يخضع لتغييرات الخدمة مستقبلاً.",
          ]}
        />
      </Section>

      <Section title="٤. المدفوعات والاسترداد">
        <p>تتم معالجة المدفوعات عبر Lemon Squeezy.</p>
        <Bullet
          items={[
            "إذا كان المخرج خاطئاً بوضوح أو فشلت المعالجة، تواصل معنا خلال ٧ أيام لاسترداد كامل.",
            "نسعى للعدل في جميع طلبات الاسترداد.",
            "لا يتم الاسترداد على رصيد تم استهلاكه بنجاح.",
            "للتواصل: iziyad.alfahhad@gmail.com",
          ]}
        />
      </Section>

      <Section title="٥. الاستخدام المقبول">
        <p>توافق على عدم:</p>
        <Bullet
          items={[
            "استخدام ApplyFast لإنشاء طلبات توظيف احتيالية أو مضللة",
            "محاولة تجاوز نظام الرصيد أو حدود الاستخدام أو التحقق من الترخيص",
            "أتمتة الطلبات بصورة تُعطل الخدمة على الآخرين",
            "استخراج أو نسخ الأوامر البرمجية أو البنية التحتية للخدمة",
            "تقديم محتوى غير قانوني أو مسيء",
            "إعادة بيع الخدمة أو منح ترخيص فرعي لها دون إذن",
          ]}
        />
      </Section>

      <Section title="٦. إخلاء المسؤولية عن المحتوى المُولَّد">
        <p>
          قد يحتوي المحتوى المُولَّد بالذكاء الاصطناعي على أخطاء أو نواقص. لا نقدم أي ضمانات
          صريحة أو ضمنية حول دقة أو اكتمال أي مخرج.
        </p>
        <p>
          لا يضمن ApplyFast الحصول على مقابلات أو وظائف. أنت المسؤول الوحيد عن المحتوى الذي تقدمه لأصحاب العمل.
        </p>
      </Section>

      <Section title="٧. الملكية الفكرية">
        <Bullet
          items={[
            "سيرتك الذاتية ووصف الوظيفة ومواد التقديم ملكٌ لك بالكامل.",
            "المخرجات المُولَّدة من مدخلاتك ملكٌ لك وبإمكانك استخدامها بحرية.",
            "منصة ApplyFast وعلامتها التجارية وأنظمتها الأساسية مملوكة لـ ApplyFast ولا يجوز تقليدها أو نسخها.",
          ]}
        />
      </Section>

      <Section title="٨. تحديد المسؤولية">
        <p>
          تُقدَّم الخدمة «كما هي» دون أي ضمان. لن يكون ApplyFast مسؤولاً عن أي أضرار غير
          مباشرة أو عرضية أو تبعية ناتجة عن استخدام الخدمة أو عدم القدرة على استخدامها،
          بما في ذلك ضياع فرص عمل أو أخطاء معالجة البيانات.
        </p>
      </Section>

      <Section title="٩. توفر الخدمة والتعديلات">
        <p>
          نحتفظ بالحق في تعديل أو تعليق أو إنهاء أي جزء من الخدمة في أي وقت. سنبذل جهوداً
          معقولة لإخطار المستخدمين بالتغييرات الجوهرية. الاستمرار في الاستخدام بعد الإخطار
          يُعدّ قبولاً للتغييرات.
        </p>
      </Section>

      <Section title="١٠. القانون الحاكم">
        <p>
          تخضع هذه الشروط لأحكام نظام{" "}
          <strong className="text-white/70">المملكة العربية السعودية</strong> وتُفسَّر وفقاً له.
          تختص المحاكم السعودية بالفصل في أي نزاعات ما لم يقتضِ القانون المعمول به في بلدك غير ذلك.
        </p>
      </Section>

      <Section title="١١. التواصل معنا">
        <p>
          أي استفسار حول شروط الاستخدام:{" "}
          <a href="mailto:iziyad.alfahhad@gmail.com" className="text-emerald-400 hover:underline">
            iziyad.alfahhad@gmail.com
          </a>
        </p>
      </Section>
    </div>
  );
}
